name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Build Eureka Naming Server Docker Image
      working-directory: ./naming-server
      run: mvn spring-boot:build-image -DskipTests